compiler/natives/src/reflect: Remove pkgPath parameter from newName.
It always had the zero value and was unused. It was removed upstream.

Related to https://github.com/golang/go/commit/9c9df65c539a0e2b1de9094382b87cc0f2748ae3 (/cc @mvdan).

Fixes:

	reflect/type.go:1451:45: cannot convert false (untyped bool constant) to string
	reflect/type.go:1451:50: too few arguments in call to newName
	reflect/type.go:1854:45: cannot convert false (untyped bool constant) to string
	reflect/type.go:1854:50: too few arguments in call to newName
	reflect/type.go:1897:45: cannot convert false (untyped bool constant) to string
	reflect/type.go:1897:50: too few arguments in call to newName
	reflect/type.go:2065:47: cannot convert false (untyped bool constant) to string
	reflect/type.go:2065:52: too few arguments in call to newName
	reflect/type.go:2260:44: cannot convert false (untyped bool constant) to string
	reflect/type.go:2260:49: too few arguments in call to newName
	reflect/type.go:2260:49: too many errors